# Generated by Django 3.0.5 on 2020-05-02 11:00

from django.db import migrations

from pandemic_back.populates.populate import set_starting_location, load_cards_locations_deck, load_connections, \
    load_locations


class Migration(migrations.Migration):
    dependencies = [
        ('pandemic', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_locations),
        migrations.RunPython(load_connections),
        migrations.RunPython(load_cards_locations_deck),
        migrations.RunPython(set_starting_location),
    ]
