# Generated by Django 3.0.5 on 2020-05-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0002_auto_20200502_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease_type',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='diseasestatus',
            name='disease_status',
            field=models.CharField(default='ongoing', max_length=10),
        ),
        migrations.AlterField(
            model_name='diseasestatus',
            name='disease_type',
            field=models.CharField(max_length=6),
        ),
    ]
