# Generated by Django 3.0.5 on 2020-05-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0003_auto_20200502_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='playroom',
            name='phase',
            field=models.CharField(default='not_started', max_length=16),
        ),
    ]
