# Generated by Django 3.0.5 on 2020-05-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0004_auto_20200502_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlocation',
            name='card',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, related_name='card_location', to='pandemic.CardsLocationDeck'),
        ),
    ]
