# Generated by Django 3.0.5 on 2020-05-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0005_auto_20200502_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfection',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_card_infections', to='pandemic.MapLocation'),
        ),
        migrations.AlterField(
            model_name='mapstate',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_map_state', to='pandemic.MapLocation'),
        ),
        migrations.AlterField(
            model_name='playroom',
            name='current_player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_player', to='pandemic.Player'),
        ),
    ]
