# Generated by Django 3.0.5 on 2020-05-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0006_auto_20200502_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='playroom',
            name='nuit_tranquille',
            field=models.BooleanField(default=False),
        ),
    ]
